# Generated by Django 3.0.2 on 2020-02-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mname', models.CharField(max_length=30)),
                ('pname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10)),
                ('noofseat', models.IntegerField()),
                ('bdate', models.DateField()),
                ('Theatre', models.CharField(max_length=30)),
            ],
        ),
    ]
